export const FETCH_BOOKS = 'FETCH_BOOKS';
export const GET_BOOK = 'GET_BOOK'; 
export const FETCH_FAVORITE_BOOKS = 'FETCH_FAVORITE_BOOKS';
export const SEARCH_BY_KEY = 'SEARCH_BY_KEY';
export const ADD_FAVORITE_BOOKS = 'ADD_FAVORITE_BOOKS';
export const GET_DETAIL_BOOK = 'GET_DETAIL_BOOK';






